@startuml

class file_system <<interface>> {
    renameVideo()
    insertVideo()
    deleteVideo()
    moveVideo()
    saveImage()
    saveCSV()
}
class barramundi_video <<entity>> {
    str:_type = "barramundi"
}
class snapper_video <<entity>>{
    str:_type = "snapper"
}
class other_fish_video <<entity>>{
    str:_type = "other"
}
note top of other_fish_video : Not a must to have.

class application_executable <<interface>> {
    executeProgram()
    useFileSystem()
}
note top of application_executable : executeProgram() will run the scripts.

user -up- application_executable : runs >

class application_main_script <<boundary>> {
    runVideoProcessing()
    runImageProcessing()
    createDashboard()
}

application_executable -left- application_main_script : executes >

class fish_video <<entity>> {
    int:_width = 1920
    int:_height = 1080
    str:_name
    int:_size
    int:_duration
}

class videos_folder <<boundary>> {
    list[]: _listofvideos
}
note top of videos_folder : Contains to-be processed videos only.

barramundi_video ..|> fish_video : generalise
snapper_video ..|> fish_video : generalise
other_fish_video ..|> fish_video : generalise

application_executable - file_system : uses >
fish_video "many" }-- "1" file_system 

file_system - videos_folder : stores >

application_main_script -down- video_processor : uses >
video_processor -down- video_processor_script : executes >

class video_processor <<interface>> {
    runScript()
}

class video_processor_script <<boundary>> {
    processImages()
    moveProcessedVideos()
    saveImages()
}

application_main_script -up- image_processor : uses >
image_processor -up- image_processor_script : executes >

class image_processor <<interface>> {
    runScript()
}

class image_processor_script <<boundary>> {
    extractText()
    extractDimensions()
    generateCSV()
}

application_main_script -left- dashboard_interface : uses >
dashboard_interface -up- dashboard_script : executes >

class dashboard_interface <<interface>> {
    buildDashboard()
}

class dashboard_script <<boundary>> {
    readCSV()
    buildStatisticModels()
}

class images_folder <<boundary>> {
    list[]: _listofimages
    list[]: _listofcompletedvideos
}
note bottom of images_folder : Delete or move the completed videos?

class output_folder <<boundary>> {
    list[]: _listofcsv
}

note bottom of output_folder: Contains completed datasets\n records of history.

file_system -down- images_folder : stores >
file_system -down- output_folder : stores >

@enduml
